### ISSUE TITLE
burst_table method fails for non-numeric alpha values in the input table

### ISSUE THREAD

**Issue by outs1der** [adellej/beans#54]
* beans version: 2.25.0
* Python version: 3.8.12
* Operating System: MacOS Ventura 13.3.1

### Description

burst_table method fails for non-numeric alpha values, as might be extracted from the MINBAR table which inserts '--' for missing data. Could make this more tolerant if there's a way to test for numeric entries

### What I Did

```
B=Beans(config_file='test.ini',corr=beans.corr_goodwin19)
B.do_run(pos='test_69.p')
B.do_analysis(['comparison'],burnin=250)
B.burst_table(key=69)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/duncan/miniforge3/envs/beans/lib/python3.8/site-packages/beansp/beans.py", line 1640, in burst_table
    bursts['alpha_obs'] = MaskedColumn(self.alpha, mask=self.alpha <=0., 
TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'float'
```

**Comment by outs1der** [comment]
Fixed with 2.26.0
