### ISSUE TITLE
plot method fails if the model is not valid

### ISSUE THREAD

**Issue by outs1der** [adellej/beans#55]
* beans version: 2.25
* Python version: 3.8.12
* Operating System: MacOS Ventura 13.3.1

### Description

Like the description says. If the current theta parameters do not produce a valid model, the ```plot``` method throws an error. 

A workaround is to set ```show_model=False``` which will prevent the model calculation, but this should be detected automatically and flagged so that it exits properly

### What I Did

```
B=Beans(config_file='test.ini',corr=beans.corr_goodwin19)
B.theta=(0.58,0.013,0.4,3,1.6,1)
B.plot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/duncan/miniforge3/envs/beans/lib/python3.8/site-packages/beansp/beans.py", line 972, in plot
    test, valid, model = runmodel(self.theta, self, match=False,
  File "/Users/duncan/miniforge3/envs/beans/lib/python3.8/site-packages/beansp/run_model.py", line 161, in runmodel
    result = generate_burst_train( bean,  Q_b, X, Z, dist, xi_p, mass, radius, debug=debug)
  File "/Users/duncan/miniforge3/envs/beans/lib/python3.8/site-packages/beansp/burstrain.py", line 335, in generate_burst_train
    mdot_max = max(smdot)
ValueError: max() arg is an empty sequence
```

**Comment by outs1der** [comment]
Fixed with 2.26.0
