### ISSUE TITLE
comparison option in do_analysis fails for ensemble mode

### ISSUE THREAD

**Issue by outs1der** [adellej/beans#58]
* beans version: 2.26.0
* Python version: 3.8.12
* Operating System: macOS Ventura 13.6.6

### Description

After running the chains in ensemble mode, you should be able to plot the comparison of the data; but this is not currently implemented for that mode.

### What I Did

```
from beansp import Beans,beans
B=Beans(config_file='canon.ini',corr=beans.corr_kepler)
B.do_run()
B.do_analysis(['comparison'],burnin=840)
Reading in and processing blobs, ignoring first 840...
...done
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/duncan/python/beans/beansp/beans.py", line 2356, in do_analysis
    
  File "/Users/duncan/python/beans/beansp/beans.py", line 2356, in <listcomp>
    
TypeError: 'int' object is not subscriptable
```

**Comment by outs1der** [comment]
fixed in v2.27.2
